### ISSUE TITLE
Incorrect Ratio Description on Profiles Page

### ISSUE THREAD

**Issue by jenmlin** [IBM-Bluemix-Docs/vpc-on-classic-vsi#1]
https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-profiles&origin_team=T02J3DPUE#using-the-cli

This talks about the old ratios (compute 1:1, balanced 1:2/1:4) 

In VPC we switched to Compute 1:2, Balanced 1:4

**Comment by gudrun-wolfgram** [comment]
Thanks @jenmlin 

It's updated here: https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-profiles

 Compute 1:2, Balanced 1:4
