### ISSUE TITLE
Classic infrastructure terminology 

### ISSUE THREAD

**Issue by donslovenkai** [IBM-Bluemix-Docs/vpc-on-classic-vsi#2]
"Classic infrastructure" is used in the opening sentence to describe the current offering (VPC on Classic).  In the subsequent Note, "classic infrastructure" is used to refer to SoftLayer classic.  As written, the dual use of this term will confuse the reader.  

The Note states Virtual Servers for VPC is incompatible with classic virtual server offerings. The next sentence also states " If you are interested in any of the IBM Cloud Virtual Servers offerings on the classic infrastructure..."  

We need a better way to refer to the Softlayer Classic infrastructure.

**Comment by gudrun-wolfgram** [comment]
Tweaked the note to not reference classic infrastructure again.
